### ISSUE TITLE
Passing Dataset

### ISSUE THREAD

**Issue by LinaZiad** [Vasanthengineer4949/NLP-Projects-NHV#2]
Hi all,

I'm currently working on fine tuning Mistral using my own dataset. But I'm wondering of how to upload the data. I used dataset = load_dataset('json', data_files='/path to the dataset/.jsonl', split='train')

But this error is showing when I run AutoModelForCausalLM.from_pretrained:
ValueError: You need to pass `dataset` in order to quantize your model

It looks like it can't see it. 

Will appreciate any help.

**Comment by Vasanthengineer4949** [comment]
It is not having a path
