### ISSUE TITLE
phi-1.5 finetuning

### ISSUE THREAD

**Issue by AlbelTec** [Vasanthengineer4949/NLP-Projects-NHV#4]
Hi,
First of all thanks for your contributions and sharing.
I'm having trouble to get inference stopped. Actually, after my fine-tuning, when I'm doing an inference. the model keep generating tokens until it reaches "max_tokens". What should I do (I'm newbie 😃) to get rid of this  and stop at the end of the answer.

Any insight ?

thanks for your feedback.

**Comment by MrZhang1996** [comment]
> Hi, First of all thanks for your contributions and sharing. I'm having trouble to get inference stopped. Actually, after my fine-tuning, when I'm doing an inference. the model keep generating tokens until it reaches "max_tokens". What should I do (I'm newbie 😃) to get rid of this and stop at the end of the answer.
> 
> Any insight ?
> 
> thanks for your feedback.

This code does not add eos_token when processing data
