### ISSUE TITLE
Device error DPO part2 notebook

### ISSUE THREAD

**Issue by LBBusser** [Vasanthengineer4949/NLP-Projects-NHV#5]
When running the notebooks out of the box, I am getting an device error when trying to train the DPO. 
Somehow something is on the cpu while it expects a CUDA device. I am running on the T4 in google colab... do you know what it could be and how to solve? Thanks!

**Comment by Vasanthengineer4949** [comment]
Please check this video: https://youtu.be/crXjRYbvT1U
